/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "PAISA_API_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PaisaMcpApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "PaisaMcpService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "PaisaMcpVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}